TILE_WIDTH = 48
TILE_HEIGHT = 48

COLUMN_COUNT = 18
ROW_COUNT = 14

SCREEN_WIDTH = COLUMN_COUNT * TILE_WIDTH
SCREEN_HEIGHT = ROW_COUNT * TILE_HEIGHT
SCREEN_TITLE = "Platformer"

CAMERA_SPEED = 0.1


PLAYER_SPEED = 4
PLAYER_JUMP_HEIGHT = 15
PLAYER_GRAVITY = 0.5

TRAP_SPIN_SPEED = 6

VIEWPORT_MARGIN = 220